# Generated by Django 5.0 on 2024-01-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='year_of_manufacture',
        ),
    ]
