# Generated by Django 5.0 on 2024-01-04 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_register', '0002_remove_clothingitem_quality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images/')),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='cloth_register.clothingitem')),
            ],
        ),
    ]
