# Generated by Django 5.0 on 2024-01-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_register', '0003_additionalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('quantity', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
    ]
