# Generated by Django 5.0 on 2024-01-06 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_register', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clothing_item',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cloth_register.clothingitem'),
            preserve_default=False,
        ),
    ]
