# Generated by Django 5.0 on 2024-01-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_register', '0006_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
