# Generated by Django 5.0.1 on 2024-01-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_register', '0009_userprofile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='NoAddress', max_length=500),
        ),
    ]
